---
title: "Resume"
---



##Noah Kreski

###Educational Background


Columbia University’s Mailman School of Public Health                            August 2017 – May 2019 (Expected)
Master of Public Health Degree Candidate, Epidemiology

New York University 							          August 2013 – December 2016
Bachelor of Arts in Psychology, Minor in Public Health
Final GPA:   4.00

###Public Health Experience

Research Assistant and Data Analyst, Mailman School of Public Health		         April 2018-Present

•	Led statistical analysis in SAS for psychiatric epidemiology research on adolescents for Dr. Katherine Keyes
•	Constructed dozens of graphical representations of research findings in SAS and R 



Research Assistant, New York University School of Medicine			         June 2016-June 2017

•	Supported research projects utilizing geospatial methods to evaluate health disparities within neighborhoods, to study the sexual and mental health of LGBTQ populations under Dr. Dustin Duncan, including author contributions to multiple papers
•	Collaboratively organized research on mental health topics for international samples men who have sex with men, from survey development and sample recruitment to the development of a first-authored paper 
•	Designed and organized materials for international presentations, funding applications, guest lectures, and IRB processes


Research Assistant, NYU Couples Lab                                                                              May 2015-May 2016

•	Coordinated recruitment of couples for studies on construal level, emotional support, and communication under Dr. Patrick Shrout
•	Managed transcription efforts documenting hours of interactions between participants for qualitative analysis
•	Workshopped technical solutions for studies incorporating audiovisual technology, coding, and video software

Research Intern, CHIBPS Lab	                                                                       September 2014 – December 2014

•	Established new venues for recruitment of MSM for studies on geographic health patterns, mental health and sexual health as part of the P18 and GPS studies under Dr. Perry Halkitis
•	Trained participants in technological aspects of studies, including GPS tracking technology for NIH-funded studies.

Outreach and Research Intern, Project Achieve	                                                May 2014-September 2014

•	Managed research documentation for multiple phase I vaccine studies 
•	Screened and recruited dozens of new participants for phase I trials of multiple vaccine studies

###Volunteer Public Health Experience

Community Advisory Board Member, HIV Vaccine Trials Network	                     December 2015 – April 2017

•	Provided youth advocacy and community feedback for HVTN’s work on injectable PrEP and health disparities
•	Critiqued dozens of documents and protocols for epidemiological studies for research organizations

Development Data Management Intern, The Hetrick-Martin Institute	   October 2015-December 2016   

•	Managed documentation for major donations from organizations and individuals, funding efforts to provide services to LGBTQ youth including housing, education, and health programs
•	Compiled volunteer and donor information into Raiser’s Edge for organizational use

Report Writer and Volunteer, Anti-Violence Project             May 2013 – June 2016 

•	   Completed 20 hours of coursework in Community Organizing and Leadership 
•	   Analyzed and consolidated data for NCAVP’s 2013 National Report on LGBT Intimate Partner Violence

###Technical Skills and Certifications

Research: SAS, R, Endnote X7, Qualtrics, SPSS, GIS
Programming:	 Coursework in CSS, HTML, Python
Design: Illustrator, After Effects, Photoshop, InDesign
Administrative:  Raiser’s Edge
Certifications:  HIPAA, CITI Human Subjects


###Publications

Duncan, D. T., Park, S. H., Goedel, W. C., Kreski, N. T., Morganstein, J. G., Hambrick, H. R., ... & Chaix, B. (2017). Perceived Neighborhood Safety Is Associated with Poor Sleep Health among Gay, Bisexual, and Other Men Who Have Sex with Men in Paris, France. Journal of Urban Health, 1-9.

Goedel WC, Reisner SL, Janssen AC, Poteat TC, Regan SD, Kreski NT, Confident G, Duncan DT. (2017). Acceptability and Feasibility of Using a Novel Geospatial Method to Measure Neighborhood Contexts and Mobility Among Transgender Women in New York City. Transgender Health, 2(1), 96-106.
Goedel, W. C., Schneider, J. A., Hambrick, H. R., Kreski, N. T., Morganstein, J. G., Park, S. H., ... & Duncan, D. T. (2018). Are Anal Sex Roles Associated with Preferences for Pre-Exposure Prophylaxis Administration Modalities Among Men Who Have Sex with Men?. Archives of sexual behavior, 47(7), 2123-2133.

Hambrick, H. R., Park, S. H., Goedel, W. C., Morganstein, J. G., Kreski, N. T., Mgbako, O., & Duncan, D. T. (2017). Rectal Douching Among Men Who Have Sex with Men in Paris: Implications for HIV/STI Risk Behaviors and Rectal Microbicide Development. AIDS and Behavior, 1-9.

Harry-Hernández S, Park SH, Mayer KH, Kreski N, Goedel WC, Hambrick HR, Brooks B, Guilamo-Ramos V, Duncan DT. Sexual Tourism, Condomless Anal Intercourse and HIV Risk Among Men Who Have Sex with Men. Journal of the Association for Nurses in AIDS Care. Accepted pending minor revisions.

Kreski, N. T., Park, S. H. N., Safren, S. A., Goedel, W. C., Morganstein, J. G., Chaix, B., & Duncan, D. T. (2018). Is Neighborhood Safety Associated with Depression Symptoms, Anxiety Symptoms, and Psychological Distress Among Gay, Bisexual, and Other Men Who Have Sex with Men?. Journal of Gay & Lesbian Mental Health, 22:3, 243-260.

### Poster Presentations

Kreski NT, Park SH, Safren SA, Goedel WC, Morganstein JG, Grace R, Duncan DT. Neighborhood Safety, Depression, Anxiety and Psychological Distress, Among Gay, Bisexual, and Other Men Who Have Sex with Men in Paris, France. Poster presentation. New York City Epidemiology Forum. New York, NY. February 2017

###Honors

•	NYU Dean’s List for all academic years, based on a GPA of 3.65 or higher for the academic year.

•	NYU LGBTQ Center award for OUTstanding Advocate for Community Health and Wellness, awarded to a single NYU student, either graduate or undergraduate, for exceptional commitment to LGBTQ health in New York City

•	NYU President’s Service Award as member of the group Project Outreach, coordinating service learning opportunities for incoming first year students around New York City

•	Full merit scholarship awarded by Columbia University’s Mailman School of Public Health
